apiVersion: 1

datasources:
  - name: InfluxDB_Spectra
    type: influxdb
    access: proxy
    url: http://spectraguard_influx:8086
    jsonData:
      version: Flux
      organization: spectraguard_org
      defaultBucket: spectraguard_bucket
    secureJsonData:
      token: my-super-secret-auth-token
